"""Generate synthetic CS3 (Arctic sea-ice retreat) fixtures.

These fixtures emulate the layout of the real NSIDC sea-ice concentration
CDR (G02202) and ERA5 single-level surface fields used by the CS3
pipeline in production. The synthetic event is patterned after September
2012, when the Arctic sea-ice extent reached the lowest level in the
satellite era. We work in a regional sector — the Beaufort/Chukchi seas —
on a regular lat/lon grid (the real NSIDC product is on a polar-stereo
grid, but the harmonisation logic does not depend on the projection).

The generator is deterministic (fixed seed) so the SHA-256 of the
fixture files is identical across machines.

Run as a script::

    python tests/fixtures/build_cs3_fixtures.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

# --- Domain --------------------------------------------------------------
# Beaufort/Chukchi seas regional sector on a regular lat/lon grid.
BBOX = (-170.0, 70.0, -130.0, 80.0)
TIME_START = pd.Timestamp("2012-09-01")
TIME_STOP = pd.Timestamp("2012-09-15")
RESOLUTION_DEG = 1.0


def _grid() -> tuple[np.ndarray, np.ndarray, pd.DatetimeIndex]:
    west, south, east, north = BBOX
    lon = np.arange(west, east + 1e-6, RESOLUTION_DEG, dtype="float32")
    lat = np.arange(south, north + 1e-6, RESOLUTION_DEG, dtype="float32")
    time = pd.date_range(TIME_START, TIME_STOP, freq="1D", inclusive="both")
    return lon, lat, time


# ---------------------------------------------------------------------------
# NSIDC-like sea-ice concentration fixture
# ---------------------------------------------------------------------------


def build_nsidc_sic(out_path: Path) -> Path:
    """Daily sea-ice concentration (fraction 0-1) with a synthetic retreat."""
    lon, lat, time = _grid()
    rng = np.random.default_rng(20120901)

    # Baseline: ice fraction increases with latitude, reaches ~1 near 80°N
    # in the climatological-ish September.
    baseline = np.clip((lat[:, None] - 70.0) / 8.0, 0.0, 1.0)
    baseline = np.broadcast_to(baseline, (lat.size, lon.size)).astype("float32")

    # Retreat structure: a low-concentration tongue intruding from the south
    # along the central Beaufort, deepening over the window.
    sic = np.empty((len(time), lat.size, lon.size), dtype="float32")
    days = np.arange(len(time), dtype="float32")
    retreat_strength = np.clip(days / max(len(time) - 1, 1), 0.0, 1.0)
    LAT2D, LON2D = np.meshgrid(lat, lon, indexing="ij")
    for ti, strength in enumerate(retreat_strength):
        # Centre near 75°N, 150°W, intruding north as the window progresses.
        cy = 73.5 + 0.6 * strength
        cx = -150.0
        retreat = (
            -0.55 * strength * np.exp(-(((LAT2D - cy) ** 2) / 4.0 + ((LON2D - cx) ** 2) / 70.0))
        )
        noise = rng.standard_normal(baseline.shape).astype("float32") * 0.03
        sic[ti] = np.clip(baseline + retreat.astype("float32") + noise, 0.0, 1.0)

    ds = xr.Dataset(
        data_vars={
            "sic": (
                ("time", "lat", "lon"),
                sic,
                {
                    "standard_name": "sea_ice_area_fraction",
                    "long_name": "Sea-ice concentration",
                    "units": "1",
                    "valid_min": np.float32(0.0),
                    "valid_max": np.float32(1.0),
                    "source": "NSIDC-like synthetic G02202 daily SIC",
                },
            )
        },
        coords={
            "time": ("time", time, {"standard_name": "time"}),
            "lat": ("lat", lat, {"standard_name": "latitude", "units": "degrees_north"}),
            "lon": ("lon", lon, {"standard_name": "longitude", "units": "degrees_east"}),
        },
        attrs={
            "title": "MOSAIC CS3 fixture — synthetic NSIDC SIC, Sep 2012",
            "Conventions": "CF-1.11",
            "history": "generated by tests/fixtures/build_cs3_fixtures.py",
            "mosaic_synthetic": "true",
        },
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    ds.to_netcdf(out_path, engine="h5netcdf")
    return out_path


# ---------------------------------------------------------------------------
# ERA5-like surface fixture (t2m, msl)
# ---------------------------------------------------------------------------


def build_era5_surface(out_path: Path) -> Path:
    """ERA5-like 2 m air temperature and mean sea-level pressure."""
    lon, lat, time = _grid()
    rng = np.random.default_rng(20120901 + 1)

    # Baseline t2m: anomalously warm summer 2012 — 274 K (1 °C) at the
    # southern edge, decreasing towards 268 K (-5 °C) in the high Arctic.
    base_t = 274.0 - (lat[:, None] - 70.0) * 0.6
    base_t = np.broadcast_to(base_t, (lat.size, lon.size)).astype("float32")

    t2m = np.empty((len(time), lat.size, lon.size), dtype="float32")
    msl = np.empty_like(t2m)
    LAT2D, LON2D = np.meshgrid(lat, lon, indexing="ij")
    days = np.arange(len(time), dtype="float32")
    warm_pulse = np.clip(days / max(len(time) - 1, 1), 0.0, 1.0)
    for ti, strength in enumerate(warm_pulse):
        # Warm anomaly co-located with the retreating ice tongue.
        warm = (
            3.0
            * strength
            * np.exp(-(((LAT2D - 74.0) ** 2) / 6.0 + ((LON2D - 150.0 * -1) ** 2) / 80.0))
        )
        t2m[ti] = (
            base_t
            + warm.astype("float32")
            + rng.standard_normal(base_t.shape).astype("float32") * 0.4
        ).astype("float32")
        # MSLP: climatological ~1013 hPa with mild high-pressure ridge that
        # promotes the warm air advection.
        msl[ti] = (
            1013.0
            + 4.0 * np.cos(np.deg2rad((lat[:, None] - 75.0) * 9.0))
            + rng.standard_normal(base_t.shape).astype("float32") * 0.3
        ).astype("float32")

    ds = xr.Dataset(
        data_vars={
            "t2m": (
                ("time", "lat", "lon"),
                t2m,
                {
                    "standard_name": "air_temperature",
                    "long_name": "2 m air temperature",
                    "units": "K",
                },
            ),
            "msl": (
                ("time", "lat", "lon"),
                msl,
                {
                    "standard_name": "air_pressure_at_mean_sea_level",
                    "long_name": "Mean sea-level pressure",
                    "units": "hPa",
                },
            ),
        },
        coords={
            "time": ("time", time, {"standard_name": "time"}),
            "lat": ("lat", lat, {"standard_name": "latitude", "units": "degrees_north"}),
            "lon": ("lon", lon, {"standard_name": "longitude", "units": "degrees_east"}),
        },
        attrs={
            "title": "MOSAIC CS3 fixture — synthetic ERA5-like Arctic surface fields",
            "Conventions": "CF-1.11",
            "history": "generated by tests/fixtures/build_cs3_fixtures.py",
            "mosaic_synthetic": "true",
        },
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    ds.to_netcdf(out_path, engine="h5netcdf")
    return out_path


# ---------------------------------------------------------------------------
# SIC climatology fixture (1991-2020 September baseline)
# ---------------------------------------------------------------------------


def build_sic_climatology(out_path: Path) -> Path:
    """A constant-in-time September SIC climatology."""
    lon, lat, time = _grid()
    # Climatological September SIC ramp: 0 at southern edge, ~1 at the north.
    clim_2d = np.clip((lat[:, None] - 70.0) / 7.0, 0.0, 1.0)
    clim_2d = np.broadcast_to(clim_2d, (lat.size, lon.size)).astype("float32")
    clim = np.broadcast_to(clim_2d, (len(time), lat.size, lon.size)).astype("float32")

    ds = xr.Dataset(
        data_vars={
            "sic_climatology": (
                ("time", "lat", "lon"),
                clim,
                {
                    "long_name": "September SIC climatology (1991-2020) — synthetic",
                    "units": "1",
                    "mosaic_role": "climatology",
                },
            )
        },
        coords={
            "time": ("time", time, {"standard_name": "time"}),
            "lat": ("lat", lat, {"standard_name": "latitude", "units": "degrees_north"}),
            "lon": ("lon", lon, {"standard_name": "longitude", "units": "degrees_east"}),
        },
        attrs={
            "title": "MOSAIC CS3 fixture — synthetic SIC climatology",
            "Conventions": "CF-1.11",
            "history": "generated by tests/fixtures/build_cs3_fixtures.py",
            "mosaic_synthetic": "true",
        },
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    ds.to_netcdf(out_path, engine="h5netcdf")
    return out_path


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def build_all(fixtures_dir: Path | None = None) -> dict[str, Path]:
    fixtures_dir = Path(fixtures_dir) if fixtures_dir else Path(__file__).parent / "cs3"
    fixtures_dir.mkdir(parents=True, exist_ok=True)
    return {
        "nsidc_sic": build_nsidc_sic(fixtures_dir / "nsidc_arctic_sic_2012-09.nc"),
        "era5_surface": build_era5_surface(fixtures_dir / "era5_arctic_surface_2012-09.nc"),
        "sic_clim": build_sic_climatology(fixtures_dir / "arctic_sic_climatology_sep.nc"),
    }


if __name__ == "__main__":  # pragma: no cover - manual invocation
    paths = build_all()
    for k, v in paths.items():
        print(f"{k}: {v}")
